---
- name: Include {{ ansible_pkg_mgr }} tasks
  include_tasks: "{{ ansible_pkg_mgr }}.yml"
  when: |
    ansible_pkg_mgr is defined
    and ansible_pkg_mgr == "apt"
    or ansible_pkg_mgr == "dnf"
  tags: googlechrome

- name: Install Google Chrome on Windows
  win_chocolatey: name=googlechrome
  when: ansible_system|lower == "win32nt"
  tags: googlechrome
