---
- name: Include tasks for {{ ansible_pkg_mgr | default('Linux') }}
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}.yml"
  when: |
    ansible_pkg_mgr is defined
    and (ansible_pkg_mgr == "apt"
    or ansible_pkg_mgr == "dnf"
    or ansible_pkg_mgr == "zypper")
  tags: googlechrome

- name: Make Google Chrome on Windows {{ googlechrome_state }}
  failed_when: false
  chocolatey.chocolatey.win_chocolatey:
    name: googlechrome
    state: "{{ googlechrome_state }}"
  when: ansible_system|lower == "win32nt"
  tags: googlechrome, win_chocolatey
