---
- name: Make repository key {{ googlechrome_state }}
  rpm_key:
    key: "{{ googlechrome_linux_signing_key_url }}"
  when: googlechrome_state != "absent"
  tags: googlechrome

- name: Make repository {{ googlechrome_state }} in the list
  zypper_repository:
    name: googlechrome
    description: googlechrome repository
    repo: "{{ googlechrome_yum_repository_url }}"
    auto_import_keys: true
    state: "{{ googlechrome_state }}"
    runrefresh: true
  tags: googlechrome

- name: Make Google Chrome {{ googlechrome_state }}
  zypper:
    name: "google-chrome-stable"
    state: "{{ googlechrome_state }}"
    update_cache: true
  tags: googlechrome
