---
- name: Add repository key
  ansible.builtin.rpm_key:
    key: "{{ googlechrome_linux_signing_key_url }}"
  when: googlechrome_state != "absent"
  tags: googlechrome

- name: Manage repository in the list
  community.general.zypper_repository:
    name: googlechrome
    description: googlechrome repository
    repo: "{{ googlechrome_yum_repository_url }}"
    auto_import_keys: true
    state: "{{ googlechrome_state }}"
    runrefresh: true
  when: googlechrome_state in ["absent", "present"]
  tags: googlechrome

- name: Make Google Chrome {{ googlechrome_state }}
  community.general.zypper:
    name: "google-chrome-stable"
    state: "{{ googlechrome_state }}"
    update_cache: true
  tags: googlechrome
